image: eosio/eosio-web-ide:v0.1.0

ports:
- port: 3000
  onOpen: allow
- port: 8000
  onOpen: allow
- port: 8080
  onOpen: allow
- port: 8888
  onOpen: allow
- port: 9876
  onOpen: allow

tasks:
- before: cd webapp
  init: yarn
  command: nginx -c $PWD/nginx.conf; npx webpack-dev-server
- before: cleos wallet unlock --password </password
  command: nodeos --config-dir ~/eosio/chain/config --data-dir ~/eosio/chain/data -e -p eosio --plugin eosio::chain_api_plugin --contracts-console

vscode:
  extensions:
    - ms-vscode.azure-account@0.8.9:uk3DSFWmuhxp+pn45DteIQ==